### ISSUE TITLE
API weirdness

### ISSUE THREAD

**Issue by boxxxie** [senecajs/seneca-cache#3]
looking at the API it seems that the user really has to do the low level tasks to get the cache working correctly, as well as being very easy to screw things up.

this is how i see interacting with your cache working

```
get() -> 
if undefined -> getVal() -> add()
return Val
```

the issue is that the user needs to call 3 functions and a conditional to get basic usability of this cache.

what would be better is if the user only needed to call `get()` and the get function did all of this other crap under the hood like this lib does http://monmohan.github.io/dsjslib/Cache.html

maybe i'm missing something with your implementation, please let me know. i've just looked at the documentation.

**Comment by boxxxie** [comment]
hey, i looked at the node-lru-cache lib, and i feel that your seneca plugin is a light wrapper around it. however i feel that the node-lru-cache has a far from intuitive API.

**Comment by rjrodger** [comment]
It's a generic message set for various caches:
* https://github.com/senecajs/seneca-redis-cache
* https://github.com/senecajs/seneca-memcached-cache
* etc

The in-memory implementation (using LRUCache) is just one option.

Use case: https://github.com/senecajs/seneca-entity-cache
